kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 30002 # ambassador
      hostPort: 8080
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    - containerPort: 30001 # ambassador
      hostPort: 8443
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 8877 # ambassador diagnose port
      hostPort: 8877
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 2181 # zookeeper
      hostPort: 2181
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 32100 # kafka Bootstrap
      hostPort: 9092
    - containerPort: 32000 # kafka bootstrap
      hostPort: 9091
    - containerPort: 32200 # kafka broker0
      hostPort: 9094            
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 5672 # RMQ
      hostPort: 5672
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp

    - containerPort: 15672 # RMQ Managment Port
      hostPort: 15672
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp

    - containerPort: 30800 # KAFKA UI
      hostPort: 8000
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp      

      