kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 80 # ambassador
      hostPort: 8081
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    - containerPort: 4433 # ambassador
      hostPort: 4433
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 8877 # ambassador diagnose port
      hostPort: 8877
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 30443
      hostPort: 443
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 2181 # zookeeper
      hostPort: 2181
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 9092 # kafka
      hostPort: 9092
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
    - containerPort: 5672 # RMQ
      hostPort: 5672
      listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
      protocol: tcp # Optional, defaults to tcp
