apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: SERVER_BASEPATH
              value: "/kibana"
#          - name: elasticsearch.hosts
#            value: "quickstart-es-http"

  http:
    tls:
      selfSignedCertificate:
        disabled: true
    
