apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-kafka-ui
  labels:
    purpose: {{ .Release.Name }}
    release: {{ .Release.Name }}    
spec:
  containers:
  - name: kafka-ui
    image: landoop/kafka-connect-ui
    env:
    - name: CONNECT_URL
      value: "http://{{ .Release.Name }}-cp-kafka-connect:8083"
