# Default values for eck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cluster:
 name: kafka-cluster

spec:
 replicas:1
 
storage:
 type: jbod

cluster_volumes:
 type: persistent-claim
 size: 5Gi
 deleteClaim: false


config:
 offsets.topic.replication.factor: 1
 transaction.state.log.replication.factor: 1
 transaction.state.log.min.isr: 1

zookeeper:
 replicas: 1
zookeeper_storage:
 type: persistent-claim
 size: 5Gi
 deleteClaim: false